### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Fail to retrieve account for eosdealeradm

### ISSUE THREAD

**Issue by HuangJie98** [dealer-platform/smartContract#1]
![Uploading image.png…]()
After I deployed the project. When accessing with a browser, the web server displays "(node:8042) UnhandledPromiseRejectionWarning: Error: Fail to retrieve account for eosdealeradm
     at new RpcError (/home/hj/dapp/node_modules/eosjs/dist/eosjs-rpcerror.js:29:28)
     at JsonRpc.<anonymous> (/home/hj/dapp/node_modules/eosjs/dist/eosjs-jsonrpc.js:121:35)
     at step (/home/hj/dapp/node_modules/eosjs/dist/eosjs-jsonrpc.js:37:23)
     at Object.next (/home/hj/dapp/node_modules/eosjs/dist/eosjs-jsonrpc.js:18:53)
     at fulfilled (/home/hj/dapp/node_modules/eosjs/dist/eosjs-jsonrpc.js:9:58)
     at process._tickCallback (internal/process/next_tick.js:68:7)
(node:8042) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch(). (rejection id: 16)". What is the reason?
Looking forward to your reply!

**Comment by sigma67** [comment]
This seems like an issue with the dapp, not the contract (this is the contract repository). You want to create an account called eosdealeradm on the target blockchain (ie your local test blockchain if using EOS Studio). Alternatively you can also change the account reference from eosdealeradm to a different account in logic/chainread and logic/chainwrite

**Comment by HuangJie98** [comment]
Thank you for your reply! Can you send me the software version that needs to be installed for this project?

**Comment by sigma67** [comment]
You can just get the latest EOS Studio version for local test: https://www.eosstudio.io/

For nodejs we used Node 14.
